steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sansan/soulsync-model', '.']

  # Step 2: Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sansan/soulsync-model']

  # Step 3: Deploy the container to Cloud Run with CPU and memory settings
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy soulsync-model-endpoint \
          --image gcr.io/$PROJECT_ID/sansan/soulsync-model \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --cpu 2 \
          --memory 4Gi

# Store images
images:
  - 'gcr.io/$PROJECT_ID/sansan/soulsync-model'
